
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ydata.exercise-plgonc.com
  resources:
  - ydata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ydata.exercise-plgonc.com
  resources:
  - ydata/finalizers
  verbs:
  - update
- apiGroups:
  - ydata.exercise-plgonc.com
  resources:
  - ydata/status
  verbs:
  - get
  - patch
  - update
